//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtencionTramites.WCF.WCFDocumentos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parametros", Namespace="http://schemas.datacontract.org/2004/07/Documentos")]
    [System.SerializableAttribute()]
    public partial class Parametros : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<AtencionTramites.WCF.WCFDocumentos.Documento> DocumentosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreMhtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcesoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<AtencionTramites.WCF.WCFDocumentos.Documento> Documentos {
            get {
                return this.DocumentosField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentosField, value) != true)) {
                    this.DocumentosField = value;
                    this.RaisePropertyChanged("Documentos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreMht {
            get {
                return this.NombreMhtField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreMhtField, value) != true)) {
                    this.NombreMhtField = value;
                    this.RaisePropertyChanged("NombreMht");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Proceso {
            get {
                return this.ProcesoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcesoField, value) != true)) {
                    this.ProcesoField = value;
                    this.RaisePropertyChanged("Proceso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Documento", Namespace="http://schemas.datacontract.org/2004/07/Documentos")]
    [System.SerializableAttribute()]
    public partial class Documento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<AtencionTramites.WCF.WCFDocumentos.Campo> CamposField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantCopiasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<AtencionTramites.WCF.WCFDocumentos.Firma> FirmasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<AtencionTramites.WCF.WCFDocumentos.Imagen> ImagenesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombrePlantillaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<AtencionTramites.WCF.WCFDocumentos.Tabla> TablasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<AtencionTramites.WCF.WCFDocumentos.Campo> Campos {
            get {
                return this.CamposField;
            }
            set {
                if ((object.ReferenceEquals(this.CamposField, value) != true)) {
                    this.CamposField = value;
                    this.RaisePropertyChanged("Campos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantCopias {
            get {
                return this.CantCopiasField;
            }
            set {
                if ((this.CantCopiasField.Equals(value) != true)) {
                    this.CantCopiasField = value;
                    this.RaisePropertyChanged("CantCopias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<AtencionTramites.WCF.WCFDocumentos.Firma> Firmas {
            get {
                return this.FirmasField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmasField, value) != true)) {
                    this.FirmasField = value;
                    this.RaisePropertyChanged("Firmas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<AtencionTramites.WCF.WCFDocumentos.Imagen> Imagenes {
            get {
                return this.ImagenesField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenesField, value) != true)) {
                    this.ImagenesField = value;
                    this.RaisePropertyChanged("Imagenes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombrePlantilla {
            get {
                return this.NombrePlantillaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombrePlantillaField, value) != true)) {
                    this.NombrePlantillaField = value;
                    this.RaisePropertyChanged("NombrePlantilla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<AtencionTramites.WCF.WCFDocumentos.Tabla> Tablas {
            get {
                return this.TablasField;
            }
            set {
                if ((object.ReferenceEquals(this.TablasField, value) != true)) {
                    this.TablasField = value;
                    this.RaisePropertyChanged("Tablas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Campo", Namespace="http://schemas.datacontract.org/2004/07/Documentos")]
    [System.SerializableAttribute()]
    public partial class Campo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorField, value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Firma", Namespace="http://schemas.datacontract.org/2004/07/Documentos")]
    [System.SerializableAttribute()]
    public partial class Firma : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombFirmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PosicionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombFirma {
            get {
                return this.NombFirmaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombFirmaField, value) != true)) {
                    this.NombFirmaField = value;
                    this.RaisePropertyChanged("NombFirma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Posicion {
            get {
                return this.PosicionField;
            }
            set {
                if ((object.ReferenceEquals(this.PosicionField, value) != true)) {
                    this.PosicionField = value;
                    this.RaisePropertyChanged("Posicion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Imagen", Namespace="http://schemas.datacontract.org/2004/07/Documentos")]
    [System.SerializableAttribute()]
    public partial class Imagen : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> AltoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> AnchoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PosicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutaImgenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Alto {
            get {
                return this.AltoField;
            }
            set {
                if ((this.AltoField.Equals(value) != true)) {
                    this.AltoField = value;
                    this.RaisePropertyChanged("Alto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Ancho {
            get {
                return this.AnchoField;
            }
            set {
                if ((this.AnchoField.Equals(value) != true)) {
                    this.AnchoField = value;
                    this.RaisePropertyChanged("Ancho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Posicion {
            get {
                return this.PosicionField;
            }
            set {
                if ((object.ReferenceEquals(this.PosicionField, value) != true)) {
                    this.PosicionField = value;
                    this.RaisePropertyChanged("Posicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RutaImgen {
            get {
                return this.RutaImgenField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaImgenField, value) != true)) {
                    this.RutaImgenField = value;
                    this.RaisePropertyChanged("RutaImgen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tabla", Namespace="http://schemas.datacontract.org/2004/07/Documentos")]
    [System.SerializableAttribute()]
    public partial class Tabla : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<AtencionTramites.WCF.WCFDocumentos.FilaResultado> FilasResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreEstiloPersonalizadoFilasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PunteroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<AtencionTramites.WCF.WCFDocumentos.FilaResultado> FilasResultado {
            get {
                return this.FilasResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.FilasResultadoField, value) != true)) {
                    this.FilasResultadoField = value;
                    this.RaisePropertyChanged("FilasResultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreEstiloPersonalizadoFilas {
            get {
                return this.NombreEstiloPersonalizadoFilasField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreEstiloPersonalizadoFilasField, value) != true)) {
                    this.NombreEstiloPersonalizadoFilasField = value;
                    this.RaisePropertyChanged("NombreEstiloPersonalizadoFilas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Puntero {
            get {
                return this.PunteroField;
            }
            set {
                if ((object.ReferenceEquals(this.PunteroField, value) != true)) {
                    this.PunteroField = value;
                    this.RaisePropertyChanged("Puntero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilaResultado", Namespace="http://schemas.datacontract.org/2004/07/Documentos")]
    [System.SerializableAttribute()]
    public partial class FilaResultado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> AltoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<AtencionTramites.WCF.WCFDocumentos.ColumnaResultado> ColumnasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> GenerarEnNuevaTablaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Alto {
            get {
                return this.AltoField;
            }
            set {
                if ((this.AltoField.Equals(value) != true)) {
                    this.AltoField = value;
                    this.RaisePropertyChanged("Alto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<AtencionTramites.WCF.WCFDocumentos.ColumnaResultado> Columnas {
            get {
                return this.ColumnasField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnasField, value) != true)) {
                    this.ColumnasField = value;
                    this.RaisePropertyChanged("Columnas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> GenerarEnNuevaTabla {
            get {
                return this.GenerarEnNuevaTablaField;
            }
            set {
                if ((this.GenerarEnNuevaTablaField.Equals(value) != true)) {
                    this.GenerarEnNuevaTablaField = value;
                    this.RaisePropertyChanged("GenerarEnNuevaTabla");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ColumnaResultado", Namespace="http://schemas.datacontract.org/2004/07/Documentos")]
    [System.SerializableAttribute()]
    public partial class ColumnaResultado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> AnchoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AtencionTramites.WCF.WCFDocumentos.Merge HorizontalMergeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AtencionTramites.WCF.WCFDocumentos.Imagen ImagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AtencionTramites.WCF.WCFDocumentos.Link LinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreEstiloPersonalizado_IndividualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AtencionTramites.WCF.WCFDocumentos.TipoBookmark TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AtencionTramites.WCF.WCFDocumentos.Merge VerticalMergeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Ancho {
            get {
                return this.AnchoField;
            }
            set {
                if ((this.AnchoField.Equals(value) != true)) {
                    this.AnchoField = value;
                    this.RaisePropertyChanged("Ancho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AtencionTramites.WCF.WCFDocumentos.Merge HorizontalMerge {
            get {
                return this.HorizontalMergeField;
            }
            set {
                if ((this.HorizontalMergeField.Equals(value) != true)) {
                    this.HorizontalMergeField = value;
                    this.RaisePropertyChanged("HorizontalMerge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AtencionTramites.WCF.WCFDocumentos.Imagen Imagen {
            get {
                return this.ImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenField, value) != true)) {
                    this.ImagenField = value;
                    this.RaisePropertyChanged("Imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AtencionTramites.WCF.WCFDocumentos.Link Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreEstiloPersonalizado_Individual {
            get {
                return this.NombreEstiloPersonalizado_IndividualField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreEstiloPersonalizado_IndividualField, value) != true)) {
                    this.NombreEstiloPersonalizado_IndividualField = value;
                    this.RaisePropertyChanged("NombreEstiloPersonalizado_Individual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AtencionTramites.WCF.WCFDocumentos.TipoBookmark Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorField, value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AtencionTramites.WCF.WCFDocumentos.Merge VerticalMerge {
            get {
                return this.VerticalMergeField;
            }
            set {
                if ((this.VerticalMergeField.Equals(value) != true)) {
                    this.VerticalMergeField = value;
                    this.RaisePropertyChanged("VerticalMerge");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Link", Namespace="http://schemas.datacontract.org/2004/07/Documentos")]
    [System.SerializableAttribute()]
    public partial class Link : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PosicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Posicion {
            get {
                return this.PosicionField;
            }
            set {
                if ((object.ReferenceEquals(this.PosicionField, value) != true)) {
                    this.PosicionField = value;
                    this.RaisePropertyChanged("Posicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto {
            get {
                return this.TextoField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoField, value) != true)) {
                    this.TextoField = value;
                    this.RaisePropertyChanged("Texto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Merge", Namespace="http://schemas.datacontract.org/2004/07/Documentos")]
    public enum Merge : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        First = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Previous = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoBookmark", Namespace="http://schemas.datacontract.org/2004/07/Documentos")]
    public enum TipoBookmark : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Adicional = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Firma = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Imagen = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hyperlink = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoGeneracion", Namespace="http://schemas.datacontract.org/2004/07/Documentos")]
    [System.SerializableAttribute()]
    public partial class ResultadoGeneracion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> ExcepcionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutaFisicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutaVirtualField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Excepciones {
            get {
                return this.ExcepcionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ExcepcionesField, value) != true)) {
                    this.ExcepcionesField = value;
                    this.RaisePropertyChanged("Excepciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((this.ResultadoField.Equals(value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RutaFisica {
            get {
                return this.RutaFisicaField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaFisicaField, value) != true)) {
                    this.RutaFisicaField = value;
                    this.RaisePropertyChanged("RutaFisica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RutaVirtual {
            get {
                return this.RutaVirtualField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaVirtualField, value) != true)) {
                    this.RutaVirtualField = value;
                    this.RaisePropertyChanged("RutaVirtual");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entrada", Namespace="http://schemas.datacontract.org/2004/07/Documentos")]
    [System.SerializableAttribute()]
    public partial class Entrada : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConnectionStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AtencionTramites.WCF.WCFDocumentos.FormatoSalida FormatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreDocumentoGeneradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<AtencionTramites.WCF.WCFDocumentos.DocumentoDB> PlantillasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AtencionTramites.WCF.WCFDocumentos.TipoDB TipoDbField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConnectionString {
            get {
                return this.ConnectionStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectionStringField, value) != true)) {
                    this.ConnectionStringField = value;
                    this.RaisePropertyChanged("ConnectionString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AtencionTramites.WCF.WCFDocumentos.FormatoSalida Formato {
            get {
                return this.FormatoField;
            }
            set {
                if ((this.FormatoField.Equals(value) != true)) {
                    this.FormatoField = value;
                    this.RaisePropertyChanged("Formato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreDocumentoGenerado {
            get {
                return this.NombreDocumentoGeneradoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreDocumentoGeneradoField, value) != true)) {
                    this.NombreDocumentoGeneradoField = value;
                    this.RaisePropertyChanged("NombreDocumentoGenerado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<AtencionTramites.WCF.WCFDocumentos.DocumentoDB> Plantillas {
            get {
                return this.PlantillasField;
            }
            set {
                if ((object.ReferenceEquals(this.PlantillasField, value) != true)) {
                    this.PlantillasField = value;
                    this.RaisePropertyChanged("Plantillas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AtencionTramites.WCF.WCFDocumentos.TipoDB TipoDb {
            get {
                return this.TipoDbField;
            }
            set {
                if ((this.TipoDbField.Equals(value) != true)) {
                    this.TipoDbField = value;
                    this.RaisePropertyChanged("TipoDb");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormatoSalida", Namespace="http://schemas.datacontract.org/2004/07/Documentos")]
    public enum FormatoSalida : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        doc = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        docx = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        pdf = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentoDB", Namespace="http://schemas.datacontract.org/2004/07/Documentos")]
    [System.SerializableAttribute()]
    public partial class DocumentoDB : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<AtencionTramites.WCF.WCFDocumentos.Campo> CamposAdicionalesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AtencionTramites.WCF.WCFDocumentos.Filtro FiltroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> FiltrosQueryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<AtencionTramites.WCF.WCFDocumentos.Firma> FirmasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FuenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<AtencionTramites.WCF.WCFDocumentos.Imagen> ImagenesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<AtencionTramites.WCF.WCFDocumentos.Link> LinksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroCopiasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<AtencionTramites.WCF.WCFDocumentos.TablaDB> TablasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<AtencionTramites.WCF.WCFDocumentos.Tabla> TablasAdicionalesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoFuenteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<AtencionTramites.WCF.WCFDocumentos.Campo> CamposAdicionales {
            get {
                return this.CamposAdicionalesField;
            }
            set {
                if ((object.ReferenceEquals(this.CamposAdicionalesField, value) != true)) {
                    this.CamposAdicionalesField = value;
                    this.RaisePropertyChanged("CamposAdicionales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AtencionTramites.WCF.WCFDocumentos.Filtro Filtro {
            get {
                return this.FiltroField;
            }
            set {
                if ((object.ReferenceEquals(this.FiltroField, value) != true)) {
                    this.FiltroField = value;
                    this.RaisePropertyChanged("Filtro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> FiltrosQuery {
            get {
                return this.FiltrosQueryField;
            }
            set {
                if ((object.ReferenceEquals(this.FiltrosQueryField, value) != true)) {
                    this.FiltrosQueryField = value;
                    this.RaisePropertyChanged("FiltrosQuery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<AtencionTramites.WCF.WCFDocumentos.Firma> Firmas {
            get {
                return this.FirmasField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmasField, value) != true)) {
                    this.FirmasField = value;
                    this.RaisePropertyChanged("Firmas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fuente {
            get {
                return this.FuenteField;
            }
            set {
                if ((object.ReferenceEquals(this.FuenteField, value) != true)) {
                    this.FuenteField = value;
                    this.RaisePropertyChanged("Fuente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<AtencionTramites.WCF.WCFDocumentos.Imagen> Imagenes {
            get {
                return this.ImagenesField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenesField, value) != true)) {
                    this.ImagenesField = value;
                    this.RaisePropertyChanged("Imagenes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<AtencionTramites.WCF.WCFDocumentos.Link> Links {
            get {
                return this.LinksField;
            }
            set {
                if ((object.ReferenceEquals(this.LinksField, value) != true)) {
                    this.LinksField = value;
                    this.RaisePropertyChanged("Links");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroCopias {
            get {
                return this.NumeroCopiasField;
            }
            set {
                if ((this.NumeroCopiasField.Equals(value) != true)) {
                    this.NumeroCopiasField = value;
                    this.RaisePropertyChanged("NumeroCopias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ruta {
            get {
                return this.RutaField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaField, value) != true)) {
                    this.RutaField = value;
                    this.RaisePropertyChanged("Ruta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<AtencionTramites.WCF.WCFDocumentos.TablaDB> Tablas {
            get {
                return this.TablasField;
            }
            set {
                if ((object.ReferenceEquals(this.TablasField, value) != true)) {
                    this.TablasField = value;
                    this.RaisePropertyChanged("Tablas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<AtencionTramites.WCF.WCFDocumentos.Tabla> TablasAdicionales {
            get {
                return this.TablasAdicionalesField;
            }
            set {
                if ((object.ReferenceEquals(this.TablasAdicionalesField, value) != true)) {
                    this.TablasAdicionalesField = value;
                    this.RaisePropertyChanged("TablasAdicionales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoFuente {
            get {
                return this.TipoFuenteField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoFuenteField, value) != true)) {
                    this.TipoFuenteField = value;
                    this.RaisePropertyChanged("TipoFuente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoDB", Namespace="http://schemas.datacontract.org/2004/07/Documentos")]
    public enum TipoDB : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SQLServer = 0,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Filtro", Namespace="http://schemas.datacontract.org/2004/07/Documentos")]
    [System.SerializableAttribute()]
    public partial class Filtro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreColumnaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AtencionTramites.WCF.WCFDocumentos.TipoFiltro TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreColumna {
            get {
                return this.NombreColumnaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreColumnaField, value) != true)) {
                    this.NombreColumnaField = value;
                    this.RaisePropertyChanged("NombreColumna");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AtencionTramites.WCF.WCFDocumentos.TipoFiltro Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorField, value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TablaDB", Namespace="http://schemas.datacontract.org/2004/07/Documentos")]
    [System.SerializableAttribute()]
    public partial class TablaDB : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> ColumnasAMostrarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AtencionTramites.WCF.WCFDocumentos.Filtro FiltroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> FiltrosQueryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FuenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PunteroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoFuenteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> ColumnasAMostrar {
            get {
                return this.ColumnasAMostrarField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnasAMostrarField, value) != true)) {
                    this.ColumnasAMostrarField = value;
                    this.RaisePropertyChanged("ColumnasAMostrar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AtencionTramites.WCF.WCFDocumentos.Filtro Filtro {
            get {
                return this.FiltroField;
            }
            set {
                if ((object.ReferenceEquals(this.FiltroField, value) != true)) {
                    this.FiltroField = value;
                    this.RaisePropertyChanged("Filtro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> FiltrosQuery {
            get {
                return this.FiltrosQueryField;
            }
            set {
                if ((object.ReferenceEquals(this.FiltrosQueryField, value) != true)) {
                    this.FiltrosQueryField = value;
                    this.RaisePropertyChanged("FiltrosQuery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fuente {
            get {
                return this.FuenteField;
            }
            set {
                if ((object.ReferenceEquals(this.FuenteField, value) != true)) {
                    this.FuenteField = value;
                    this.RaisePropertyChanged("Fuente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Puntero {
            get {
                return this.PunteroField;
            }
            set {
                if ((object.ReferenceEquals(this.PunteroField, value) != true)) {
                    this.PunteroField = value;
                    this.RaisePropertyChanged("Puntero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoFuente {
            get {
                return this.TipoFuenteField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoFuenteField, value) != true)) {
                    this.TipoFuenteField = value;
                    this.RaisePropertyChanged("TipoFuente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoFiltro", Namespace="http://schemas.datacontract.org/2004/07/Documentos")]
    public enum TipoFiltro : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Entero = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Texto = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntradaCPS", Namespace="http://schemas.datacontract.org/2004/07/Documentos")]
    [System.SerializableAttribute()]
    public partial class EntradaCPS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConnectionStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FormatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreDocumentoGeneradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<AtencionTramites.WCF.WCFDocumentos.DocumentoDB> PlantillasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoDbField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConnectionString {
            get {
                return this.ConnectionStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectionStringField, value) != true)) {
                    this.ConnectionStringField = value;
                    this.RaisePropertyChanged("ConnectionString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Formato {
            get {
                return this.FormatoField;
            }
            set {
                if ((this.FormatoField.Equals(value) != true)) {
                    this.FormatoField = value;
                    this.RaisePropertyChanged("Formato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreDocumentoGenerado {
            get {
                return this.NombreDocumentoGeneradoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreDocumentoGeneradoField, value) != true)) {
                    this.NombreDocumentoGeneradoField = value;
                    this.RaisePropertyChanged("NombreDocumentoGenerado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<AtencionTramites.WCF.WCFDocumentos.DocumentoDB> Plantillas {
            get {
                return this.PlantillasField;
            }
            set {
                if ((object.ReferenceEquals(this.PlantillasField, value) != true)) {
                    this.PlantillasField = value;
                    this.RaisePropertyChanged("Plantillas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoDb {
            get {
                return this.TipoDbField;
            }
            set {
                if ((this.TipoDbField.Equals(value) != true)) {
                    this.TipoDbField = value;
                    this.RaisePropertyChanged("TipoDb");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="WCFDocumentos", ConfigurationName="WCFDocumentos.IWCFDocumentos")]
    public interface IWCFDocumentos {
        
        [System.ServiceModel.OperationContractAttribute(Action="WCFDocumentos/IWCFDocumentos/GenerarDocumentoObj", ReplyAction="WCFDocumentos/IWCFDocumentos/GenerarDocumentoObjResponse")]
        AtencionTramites.WCF.WCFDocumentos.ResultadoGeneracion GenerarDocumentoObj(AtencionTramites.WCF.WCFDocumentos.Parametros inObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="WCFDocumentos/IWCFDocumentos/GenerarDocumentoObj", ReplyAction="WCFDocumentos/IWCFDocumentos/GenerarDocumentoObjResponse")]
        System.Threading.Tasks.Task<AtencionTramites.WCF.WCFDocumentos.ResultadoGeneracion> GenerarDocumentoObjAsync(AtencionTramites.WCF.WCFDocumentos.Parametros inObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="WCFDocumentos/IWCFDocumentos/GenerarDocumentoXml", ReplyAction="WCFDocumentos/IWCFDocumentos/GenerarDocumentoXmlResponse")]
        AtencionTramites.WCF.WCFDocumentos.ResultadoGeneracion GenerarDocumentoXml(string strXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="WCFDocumentos/IWCFDocumentos/GenerarDocumentoXml", ReplyAction="WCFDocumentos/IWCFDocumentos/GenerarDocumentoXmlResponse")]
        System.Threading.Tasks.Task<AtencionTramites.WCF.WCFDocumentos.ResultadoGeneracion> GenerarDocumentoXmlAsync(string strXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="WCFDocumentos/IWCFDocumentos/GenerarDocumento", ReplyAction="WCFDocumentos/IWCFDocumentos/GenerarDocumentoResponse")]
        AtencionTramites.WCF.WCFDocumentos.ResultadoGeneracion GenerarDocumento(AtencionTramites.WCF.WCFDocumentos.Entrada obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="WCFDocumentos/IWCFDocumentos/GenerarDocumento", ReplyAction="WCFDocumentos/IWCFDocumentos/GenerarDocumentoResponse")]
        System.Threading.Tasks.Task<AtencionTramites.WCF.WCFDocumentos.ResultadoGeneracion> GenerarDocumentoAsync(AtencionTramites.WCF.WCFDocumentos.Entrada obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="WCFDocumentos/IWCFDocumentos/GenerarDocumentoCPS", ReplyAction="WCFDocumentos/IWCFDocumentos/GenerarDocumentoCPSResponse")]
        AtencionTramites.WCF.WCFDocumentos.ResultadoGeneracion GenerarDocumentoCPS(AtencionTramites.WCF.WCFDocumentos.EntradaCPS obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="WCFDocumentos/IWCFDocumentos/GenerarDocumentoCPS", ReplyAction="WCFDocumentos/IWCFDocumentos/GenerarDocumentoCPSResponse")]
        System.Threading.Tasks.Task<AtencionTramites.WCF.WCFDocumentos.ResultadoGeneracion> GenerarDocumentoCPSAsync(AtencionTramites.WCF.WCFDocumentos.EntradaCPS obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="WCFDocumentos/IWCFDocumentos/GetBookmarks", ReplyAction="WCFDocumentos/IWCFDocumentos/GetBookmarksResponse")]
        string GetBookmarks(string DirPlantilla, string label);
        
        [System.ServiceModel.OperationContractAttribute(Action="WCFDocumentos/IWCFDocumentos/GetBookmarks", ReplyAction="WCFDocumentos/IWCFDocumentos/GetBookmarksResponse")]
        System.Threading.Tasks.Task<string> GetBookmarksAsync(string DirPlantilla, string label);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFDocumentosChannel : AtencionTramites.WCF.WCFDocumentos.IWCFDocumentos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFDocumentosClient : System.ServiceModel.ClientBase<AtencionTramites.WCF.WCFDocumentos.IWCFDocumentos>, AtencionTramites.WCF.WCFDocumentos.IWCFDocumentos {
        
        public WCFDocumentosClient() {
        }
        
        public WCFDocumentosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFDocumentosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFDocumentosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFDocumentosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AtencionTramites.WCF.WCFDocumentos.ResultadoGeneracion GenerarDocumentoObj(AtencionTramites.WCF.WCFDocumentos.Parametros inObj) {
            return base.Channel.GenerarDocumentoObj(inObj);
        }
        
        public System.Threading.Tasks.Task<AtencionTramites.WCF.WCFDocumentos.ResultadoGeneracion> GenerarDocumentoObjAsync(AtencionTramites.WCF.WCFDocumentos.Parametros inObj) {
            return base.Channel.GenerarDocumentoObjAsync(inObj);
        }
        
        public AtencionTramites.WCF.WCFDocumentos.ResultadoGeneracion GenerarDocumentoXml(string strXml) {
            return base.Channel.GenerarDocumentoXml(strXml);
        }
        
        public System.Threading.Tasks.Task<AtencionTramites.WCF.WCFDocumentos.ResultadoGeneracion> GenerarDocumentoXmlAsync(string strXml) {
            return base.Channel.GenerarDocumentoXmlAsync(strXml);
        }
        
        public AtencionTramites.WCF.WCFDocumentos.ResultadoGeneracion GenerarDocumento(AtencionTramites.WCF.WCFDocumentos.Entrada obj) {
            return base.Channel.GenerarDocumento(obj);
        }
        
        public System.Threading.Tasks.Task<AtencionTramites.WCF.WCFDocumentos.ResultadoGeneracion> GenerarDocumentoAsync(AtencionTramites.WCF.WCFDocumentos.Entrada obj) {
            return base.Channel.GenerarDocumentoAsync(obj);
        }
        
        public AtencionTramites.WCF.WCFDocumentos.ResultadoGeneracion GenerarDocumentoCPS(AtencionTramites.WCF.WCFDocumentos.EntradaCPS obj) {
            return base.Channel.GenerarDocumentoCPS(obj);
        }
        
        public System.Threading.Tasks.Task<AtencionTramites.WCF.WCFDocumentos.ResultadoGeneracion> GenerarDocumentoCPSAsync(AtencionTramites.WCF.WCFDocumentos.EntradaCPS obj) {
            return base.Channel.GenerarDocumentoCPSAsync(obj);
        }
        
        public string GetBookmarks(string DirPlantilla, string label) {
            return base.Channel.GetBookmarks(DirPlantilla, label);
        }
        
        public System.Threading.Tasks.Task<string> GetBookmarksAsync(string DirPlantilla, string label) {
            return base.Channel.GetBookmarksAsync(DirPlantilla, label);
        }
    }
}
